# Form implementation generated from reading ui file 'c:\dev\ws-py\QPos\ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qpos.asset import resource_rc
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 648)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#menu_widget, #toolBox {\n"
"    background-color: #3333FF;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.stacked_menu = QtWidgets.QStackedWidget(parent=self.splitter)
        self.stacked_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.stacked_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stacked_menu.setFont(font)
        self.stacked_menu.setStyleSheet("background-color: #06162d;\n"
"color: #fff;\n"
"border: none;")
        self.stacked_menu.setObjectName("stacked_menu")
        self.page_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.page_1.setFont(font)
        self.page_1.setObjectName("page_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(parent=self.page_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("#toolBox {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#toolBox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#toolBox::tab:selected {\n"
"    background-color: #2d9cdb;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#toolBox QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#toolBox QPushButton:hover {\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#toolBox QPushButton:checked {\n"
"    background-color: #3498DB;\n"
"}\n"
"\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.general_page = QtWidgets.QWidget()
        self.general_page.setGeometry(QtCore.QRect(0, 0, 132, 513))
        self.general_page.setObjectName("general_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.general_page)
        self.verticalLayout.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnHome = QtWidgets.QPushButton(parent=self.general_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnHome.setFont(font)
        self.btnHome.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnHome.setStyleSheet("")
        self.btnHome.setCheckable(True)
        self.btnHome.setChecked(True)
        self.btnHome.setObjectName("btnHome")
        self.verticalLayout.addWidget(self.btnHome)
        self.btnDashboard = QtWidgets.QPushButton(parent=self.general_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnDashboard.setStyleSheet("")
        self.btnDashboard.setCheckable(True)
        self.btnDashboard.setObjectName("btnDashboard")
        self.verticalLayout.addWidget(self.btnDashboard)
        self.btnCheckout = QtWidgets.QPushButton(parent=self.general_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCheckout.setFont(font)
        self.btnCheckout.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnCheckout.setCheckable(True)
        self.btnCheckout.setObjectName("btnCheckout")
        self.verticalLayout.addWidget(self.btnCheckout)
        self.btnCustomer = QtWidgets.QPushButton(parent=self.general_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCustomer.setFont(font)
        self.btnCustomer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnCustomer.setCheckable(True)
        self.btnCustomer.setObjectName("btnCustomer")
        self.verticalLayout.addWidget(self.btnCustomer)
        self.btnTransaction = QtWidgets.QPushButton(parent=self.general_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnTransaction.setFont(font)
        self.btnTransaction.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnTransaction.setCheckable(True)
        self.btnTransaction.setObjectName("btnTransaction")
        self.verticalLayout.addWidget(self.btnTransaction)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/home-48w.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.general_page, icon, "")
        self.manage_page = QtWidgets.QWidget()
        self.manage_page.setGeometry(QtCore.QRect(0, 0, 132, 513))
        self.manage_page.setObjectName("manage_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.manage_page)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnOrder = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnOrder.setFont(font)
        self.btnOrder.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnOrder.setCheckable(True)
        self.btnOrder.setObjectName("btnOrder")
        self.verticalLayout_2.addWidget(self.btnOrder)
        self.btnItem = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnItem.setFont(font)
        self.btnItem.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnItem.setCheckable(True)
        self.btnItem.setObjectName("btnItem")
        self.verticalLayout_2.addWidget(self.btnItem)
        self.btnInvoice = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnInvoice.setFont(font)
        self.btnInvoice.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnInvoice.setCheckable(True)
        self.btnInvoice.setObjectName("btnInvoice")
        self.verticalLayout_2.addWidget(self.btnInvoice)
        self.btnReport = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnReport.setFont(font)
        self.btnReport.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnReport.setCheckable(True)
        self.btnReport.setObjectName("btnReport")
        self.verticalLayout_2.addWidget(self.btnReport)
        self.btnVendor = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnVendor.setFont(font)
        self.btnVendor.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnVendor.setCheckable(True)
        self.btnVendor.setObjectName("btnVendor")
        self.verticalLayout_2.addWidget(self.btnVendor)
        self.btnBillpay = QtWidgets.QPushButton(parent=self.manage_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnBillpay.setFont(font)
        self.btnBillpay.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnBillpay.setObjectName("btnBillpay")
        self.verticalLayout_2.addWidget(self.btnBillpay)
        spacerItem1 = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/more-48w.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.manage_page, icon1, "")
        self.business_page = QtWidgets.QWidget()
        self.business_page.setGeometry(QtCore.QRect(0, 0, 132, 513))
        self.business_page.setObjectName("business_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.business_page)
        self.verticalLayout_3.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnMerchant = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnMerchant.setFont(font)
        self.btnMerchant.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnMerchant.setCheckable(True)
        self.btnMerchant.setObjectName("btnMerchant")
        self.verticalLayout_3.addWidget(self.btnMerchant)
        self.btnLocation = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLocation.setFont(font)
        self.btnLocation.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnLocation.setCheckable(True)
        self.btnLocation.setObjectName("btnLocation")
        self.verticalLayout_3.addWidget(self.btnLocation)
        self.btnTeam = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnTeam.setFont(font)
        self.btnTeam.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnTeam.setCheckable(True)
        self.btnTeam.setObjectName("btnTeam")
        self.verticalLayout_3.addWidget(self.btnTeam)
        self.btnShift = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnShift.setFont(font)
        self.btnShift.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnShift.setCheckable(True)
        self.btnShift.setObjectName("btnShift")
        self.verticalLayout_3.addWidget(self.btnShift)
        self.btnPayroll = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPayroll.setFont(font)
        self.btnPayroll.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnPayroll.setCheckable(True)
        self.btnPayroll.setObjectName("btnPayroll")
        self.verticalLayout_3.addWidget(self.btnPayroll)
        self.btnBank = QtWidgets.QPushButton(parent=self.business_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnBank.setFont(font)
        self.btnBank.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnBank.setObjectName("btnBank")
        self.verticalLayout_3.addWidget(self.btnBank)
        spacerItem2 = QtWidgets.QSpacerItem(20, 388, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/cog-48w.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.business_page, icon2, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.stacked_menu.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tboxItem = QtWidgets.QToolBox(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tboxItem.setFont(font)
        self.tboxItem.setStyleSheet("#tboxItem {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#tboxItem::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#tboxItem::tab:selected {\n"
"    background-color: #2d9cdb;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#tboxItem QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#tboxItem QPushButton:hover {\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#tboxItem QPushButton:checked {\n"
"    background-color: #3498DB;\n"
"}\n"
"\n"
"")
        self.tboxItem.setObjectName("tboxItem")
        self.item_page = QtWidgets.QWidget()
        self.item_page.setGeometry(QtCore.QRect(0, 0, 132, 591))
        self.item_page.setObjectName("item_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.item_page)
        self.verticalLayout_5.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnItemLib = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnItemLib.setFont(font)
        self.btnItemLib.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnItemLib.setCheckable(True)
        self.btnItemLib.setObjectName("btnItemLib")
        self.verticalLayout_5.addWidget(self.btnItemLib)
        self.btnInventoryMgt = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnInventoryMgt.setFont(font)
        self.btnInventoryMgt.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnInventoryMgt.setObjectName("btnInventoryMgt")
        self.verticalLayout_5.addWidget(self.btnInventoryMgt)
        self.btnServiceLib = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnServiceLib.setFont(font)
        self.btnServiceLib.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnServiceLib.setCheckable(True)
        self.btnServiceLib.setObjectName("btnServiceLib")
        self.verticalLayout_5.addWidget(self.btnServiceLib)
        self.btnModifier = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnModifier.setFont(font)
        self.btnModifier.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnModifier.setCheckable(True)
        self.btnModifier.setObjectName("btnModifier")
        self.verticalLayout_5.addWidget(self.btnModifier)
        self.btnCategory = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCategory.setFont(font)
        self.btnCategory.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnCategory.setCheckable(True)
        self.btnCategory.setObjectName("btnCategory")
        self.verticalLayout_5.addWidget(self.btnCategory)
        self.btnDiscount = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDiscount.setFont(font)
        self.btnDiscount.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnDiscount.setCheckable(True)
        self.btnDiscount.setObjectName("btnDiscount")
        self.verticalLayout_5.addWidget(self.btnDiscount)
        self.btnUnit = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnUnit.setFont(font)
        self.btnUnit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnUnit.setObjectName("btnUnit")
        self.verticalLayout_5.addWidget(self.btnUnit)
        self.btnItemSetting = QtWidgets.QPushButton(parent=self.item_page)
        self.btnItemSetting.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnItemSetting.setObjectName("btnItemSetting")
        self.verticalLayout_5.addWidget(self.btnItemSetting)
        spacerItem3 = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.btnItem2Home = QtWidgets.QPushButton(parent=self.item_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnItem2Home.setFont(font)
        self.btnItem2Home.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnItem2Home.setObjectName("btnItem2Home")
        self.verticalLayout_5.addWidget(self.btnItem2Home)
        self.tboxItem.addItem(self.item_page, icon1, "")
        self.verticalLayout_6.addWidget(self.tboxItem)
        self.stacked_menu.addWidget(self.page_2)
        self.main_widget = QtWidgets.QWidget(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_widget.setFont(font)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.search_widget = QtWidgets.QWidget(parent=self.main_widget)
        self.search_widget.setStyleSheet("#search_widget {background-color: #ABB2B9;}")
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSidemenu = QtWidgets.QPushButton(parent=self.search_widget)
        self.btnSidemenu.setMinimumSize(QtCore.QSize(30, 30))
        self.btnSidemenu.setMaximumSize(QtCore.QSize(30, 30))
        self.btnSidemenu.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-96-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/burger-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btnSidemenu.setIcon(icon3)
        self.btnSidemenu.setIconSize(QtCore.QSize(15, 15))
        self.btnSidemenu.setCheckable(True)
        self.btnSidemenu.setObjectName("btnSidemenu")
        self.horizontalLayout.addWidget(self.btnSidemenu)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.search_frame = QtWidgets.QFrame(parent=self.search_widget)
        self.search_frame.setMinimumSize(QtCore.QSize(300, 30))
        self.search_frame.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_frame.setFont(font)
        self.search_frame.setStyleSheet("#search_frame {\n"
"    border:  1px solid #aa7e6f;\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#search_btn {\n"
"    padding:5px 5px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#search_btn:pressed {\n"
"    padding-left: 10px;\n"
"}")
        self.search_frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout_10.setContentsMargins(15, 0, 5, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.search_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        self.search_btn = QtWidgets.QPushButton(parent=self.search_frame)
        self.search_btn.setStyleSheet("")
        self.search_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/search-3-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon4)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_10.addWidget(self.search_btn)
        self.horizontalLayout.addWidget(self.search_frame)
        spacerItem5 = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.auth_user = QtWidgets.QPushButton(parent=self.search_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auth_user.sizePolicy().hasHeightForWidth())
        self.auth_user.setSizePolicy(sizePolicy)
        self.auth_user.setMinimumSize(QtCore.QSize(30, 30))
        self.auth_user.setMaximumSize(QtCore.QSize(30, 30))
        self.auth_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.auth_user.setStyleSheet("border-radius : 15; \n"
"background-color: white;")
        self.auth_user.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/user-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.auth_user.setIcon(icon5)
        self.auth_user.setIconSize(QtCore.QSize(20, 20))
        self.auth_user.setFlat(True)
        self.auth_user.setObjectName("auth_user")
        self.horizontalLayout.addWidget(self.auth_user)
        self.gridLayout_4.addWidget(self.search_widget, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    margin-left: 3px;\n"
"    image: url(:/icon/icon/x-mark-4-32.ico)\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    \n"
"    image: url(:/icon/icon/x-mark-4-48.ico);\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(10, 10))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_4.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_menu.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(10)
        self.tboxItem.setCurrentIndex(0)
        self.tboxItem.layout().setSpacing(10)
        self.tabWidget.setCurrentIndex(-1)
        self.btnSidemenu.toggled['bool'].connect(self.stacked_menu.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QPos"))
        self.btnHome.setText(_translate("MainWindow", "Home"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnCheckout.setText(_translate("MainWindow", "Checkout"))
        self.btnCustomer.setText(_translate("MainWindow", "Customer"))
        self.btnTransaction.setText(_translate("MainWindow", "Transactions"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.general_page), _translate("MainWindow", "General"))
        self.btnOrder.setText(_translate("MainWindow", "Orders"))
        self.btnItem.setText(_translate("MainWindow", "Items"))
        self.btnInvoice.setText(_translate("MainWindow", "Invoices"))
        self.btnReport.setText(_translate("MainWindow", "Reports"))
        self.btnVendor.setText(_translate("MainWindow", "Vendors"))
        self.btnBillpay.setText(_translate("MainWindow", "Bill Pay"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.manage_page), _translate("MainWindow", "Logistic"))
        self.btnMerchant.setText(_translate("MainWindow", "Merchant"))
        self.btnLocation.setText(_translate("MainWindow", "Locations"))
        self.btnTeam.setText(_translate("MainWindow", "Teams"))
        self.btnShift.setText(_translate("MainWindow", "Shifts"))
        self.btnPayroll.setText(_translate("MainWindow", "Payroll"))
        self.btnBank.setText(_translate("MainWindow", "Bank Accounts"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.business_page), _translate("MainWindow", "Business"))
        self.btnItemLib.setText(_translate("MainWindow", "Item library"))
        self.btnInventoryMgt.setText(_translate("MainWindow", "Inventory mgt"))
        self.btnServiceLib.setText(_translate("MainWindow", "Service library"))
        self.btnModifier.setText(_translate("MainWindow", "Modifiers"))
        self.btnCategory.setText(_translate("MainWindow", "Categories"))
        self.btnDiscount.setText(_translate("MainWindow", "Discounts"))
        self.btnUnit.setText(_translate("MainWindow", "Unit"))
        self.btnItemSetting.setText(_translate("MainWindow", "Settings"))
        self.btnItem2Home.setText(_translate("MainWindow", "Home"))
        self.tboxItem.setItemText(self.tboxItem.indexOf(self.item_page), _translate("MainWindow", "Items"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Search Something..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

