from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 900)
        Form.setMinimumSize(QtCore.QSize(1500, 900))
        Form.setMaximumSize(QtCore.QSize(1500, 900))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setMinimumSize(QtCore.QSize(170, 100))
        self.timeLabel.setMaximumSize(QtCore.QSize(170, 100))
        self.timeLabel.setStyleSheet("font: 75 35pt \"Sego UI\";")
        self.timeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_2.addWidget(self.timeLabel)
        self.timeBox = QtWidgets.QTextBrowser(Form)
        self.timeBox.setMinimumSize(QtCore.QSize(300, 100))
        self.timeBox.setMaximumSize(QtCore.QSize(300, 100))
        self.timeBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.timeBox.setObjectName("timeBox")
        self.horizontalLayout_2.addWidget(self.timeBox)
        spacerItem = QtWidgets.QSpacerItem(200, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goBackBtn = QtWidgets.QPushButton(Form)
        self.goBackBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.goBackBtn.setMaximumSize(QtCore.QSize(400, 100))
        font = QtGui.QFont()
        font.setFamily("Sego UI")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.goBackBtn.setFont(font)
        self.goBackBtn.setStyleSheet("font: 75 35pt \"Sego UI\";\n"
"background-color: rgb(255, 129, 112);")
        self.goBackBtn.setObjectName("goBackBtn")
        self.horizontalLayout.addWidget(self.goBackBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 77, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.addProductBtn = QtWidgets.QPushButton(Form)
        self.addProductBtn.setMinimumSize(QtCore.QSize(400, 200))
        self.addProductBtn.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Sego UI")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.addProductBtn.setFont(font)
        self.addProductBtn.setStyleSheet("font: 75 50pt \"Sego UI\";\n"
"background-color: rgb(82, 209, 255);")
        self.addProductBtn.setObjectName("addProductBtn")
        self.horizontalLayout_3.addWidget(self.addProductBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.deleteProductBtn = QtWidgets.QPushButton(Form)
        self.deleteProductBtn.setMinimumSize(QtCore.QSize(400, 200))
        self.deleteProductBtn.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Sego UI")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.deleteProductBtn.setFont(font)
        self.deleteProductBtn.setStyleSheet("font: 75 50pt \"Sego UI\";\n"
"background-color: rgb(171, 255, 115);")
        self.deleteProductBtn.setObjectName("deleteProductBtn")
        self.horizontalLayout_3.addWidget(self.deleteProductBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.changePriceBtn = QtWidgets.QPushButton(Form)
        self.changePriceBtn.setMinimumSize(QtCore.QSize(400, 200))
        self.changePriceBtn.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Sego UI")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.changePriceBtn.setFont(font)
        self.changePriceBtn.setStyleSheet("font: 75 50pt \"Sego UI\";\n"
"background-color: rgb(222, 175, 255);")
        self.changePriceBtn.setObjectName("changePriceBtn")
        self.horizontalLayout_3.addWidget(self.changePriceBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Choose Product Management"))
        self.timeLabel.setText(_translate("Form", "Time: "))
        self.goBackBtn.setText(_translate("Form", "Go Back"))
        self.addProductBtn.setText(_translate("Form", "Add Item"))
        self.deleteProductBtn.setText(_translate("Form", "Delete Item"))
        self.changePriceBtn.setText(_translate("Form", "Price Change"))

